### ISSUE TITLE
CornerRadius property doesn't work

### ISSUE THREAD

**Issue by bubudrc** [herinkc/HTPressableButton#38]
If I tried to set a different cornerRadius property, for HTPressableButtonStyleRounded but I couldn't. Never change the value of that property.

I take a look to the code, and you set always:

**FILE:** HTPressableButton.m
**LINE:** 62

    case HTPressableButtonStyleRounded:
            _cornerRadius = 10.0;

So, the property never change.

**Comment by herinkc** [comment]
@bubudrc Thanks for the catch! :+1:
