### ISSUE TITLE
Circular buttons disabled state frame

### ISSUE THREAD

**Issue by lukenewman** [herinkc/HTPressableButton#44]
When I disable a circular button, it's frame is increased by about 5px in two directions. When it is re-enabled, it goes back to its normal size. Is this expected?

**Comment by herinkc** [comment]
Hello!

It is definitely not expected. Do you mind showing your code?  It'll help us check faster since we haven't faced this issue before.


Thanks,

**Comment by lukenewman** [comment]
I create my button like this:

    func drawPlusButton() {
        let buttonFrame = CGRectMake(0, 0, 70, 70)
        
        plusButton = HTPressableButton(frame: buttonFrame, buttonStyle: HTPressableButtonStyle.Circular)
        plusButton.buttonColor = FlatGreen()
        plusButton.shadowColor = FlatGreenDark()
        plusButton.disabledButtonColor = FlatGray()
        
        plusButton.setTitle("MORE", forState: UIControlState.Normal)
        
        plusButton.addTarget(self, action: "addPlayer", forControlEvents: UIControlEvents.TouchUpInside)
        
        self.view.addSubview(plusButton)
        
        plusButton.snp_makeConstraints { (make) -> Void in
            make.centerY.equalTo(self.view)
            make.right.equalTo(self.view).offset(-30)
        }
    }

`plusButton` is declared outside the function. The enabling logic is as follows:

    if numberOfPlayers == minNumberOfPlayers {
        minusButton.enabled = true
    }
        
    numberOfPlayers++
    if numberOfPlayers >= maxNumberOfPlayers {
        numberOfPlayers = maxNumberOfPlayers
        plusButton.enabled = false
    }

**Comment by lukenewman** [comment]
Here is the button enabled:
<img width="352" alt="screen shot 2015-09-28 at 3 12 33 pm" src="https://cloud.githubusercontent.com/assets/5315645/10145822/6d7b4802-65f3-11e5-9dea-1916882cfc32.png">

And disabled:
<img width="342" alt="screen shot 2015-09-28 at 3 12 39 pm" src="https://cloud.githubusercontent.com/assets/5315645/10145823/6d7bcb1a-65f3-11e5-8813-fd501cf85d50.png">

**Comment by tandavas** [comment]
Hi! 

Thank you for the details info and screenshot.

Could you please try to log out the width and height of the button both *before* and *after* you disable the buttons?

Like:

```objective-c
   //Circular mint color button
    frame = CGRectMake(110, 300, 100, 90);
    HTPressableButton *circularButton = [[HTPressableButton alloc] initWithFrame:frame buttonStyle:HTPressableButtonStyleCircular];
    circularButton.buttonColor = [UIColor ht_mintColor];
    circularButton.shadowColor = [UIColor ht_mintDarkColor];
    [circularButton setDisabledButtonColor:[UIColor ht_sunflowerColor]];
    [circularButton setTitle:@"Circular" forState:UIControlStateNormal];
    [self.view addSubview:circularButton];

    // Print out the width and height
    NSLog(@"widith = %f", circularButton.frame.size.width);
    NSLog(@"height = %f", circularButton.frame.size.height);
```

Then, print them out again after you disable the buttons

```
    // Print out the width and height
    NSLog(@"widith = %f", circularButton.frame.size.width);
    NSLog(@"height = %f", circularButton.frame.size.height);
```

Let me know the results.
